"""empty message

Revision ID: 5d7993cebfda
Revises: 26bec75584e5
Create Date: 2018-04-03 13:52:18.520108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d7993cebfda'
down_revision = '26bec75584e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('pwd', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('info', sa.String(length=100), nullable=True),
    sa.Column('face', sa.String(length=255), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('face'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_member_addtime'), 'member', ['addtime'], unique=False)
    op.create_table('memberlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberlog_addtime'), 'memberlog', ['addtime'], unique=False)
    op.drop_index('account', table_name='user')
    op.drop_index('face', table_name='user')
    op.drop_index('ix_user_addtime', table_name='user')
    op.drop_index('mobile', table_name='user')
    op.drop_index('nickname', table_name='user')
    op.drop_index('uuid', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_userlog_addtime', table_name='userlog')
    op.drop_table('userlog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userlog',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('addtime', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userlog_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_userlog_addtime', 'userlog', ['addtime'], unique=False)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('account', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pwd', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mobile', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('face', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('addtime', mysql.DATETIME(), nullable=True),
    sa.Column('uuid', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('uuid', 'user', ['uuid'], unique=True)
    op.create_index('nickname', 'user', ['nickname'], unique=True)
    op.create_index('mobile', 'user', ['mobile'], unique=True)
    op.create_index('ix_user_addtime', 'user', ['addtime'], unique=False)
    op.create_index('face', 'user', ['face'], unique=True)
    op.create_index('account', 'user', ['account'], unique=True)
    op.drop_index(op.f('ix_memberlog_addtime'), table_name='memberlog')
    op.drop_table('memberlog')
    op.drop_index(op.f('ix_member_addtime'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
