"""empty message

Revision ID: 11dcd1db146e
Revises: 8c77036bbd97
Create Date: 2018-04-13 16:55:28.818515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dcd1db146e'
down_revision = '8c77036bbd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('net_asset', sa.Float(), nullable=True),
    sa.Column('debt', sa.Float(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('asset', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_home_create_time'), 'home', ['create_time'], unique=False)
    op.create_table('homelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=True),
    sa.Column('edit_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homelog_edit_time'), 'homelog', ['edit_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homelog_edit_time'), table_name='homelog')
    op.drop_table('homelog')
    op.drop_index(op.f('ix_home_create_time'), table_name='home')
    op.drop_table('home')
    # ### end Alembic commands ###
