"""empty message

Revision ID: 541a2d8199ff
Revises: e978f118fd91
Create Date: 2018-04-05 09:03:31.686618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541a2d8199ff'
down_revision = 'e978f118fd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('is_super', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'is_super')
    # ### end Alembic commands ###
