"""empty message

Revision ID: 8c77036bbd97
Revises: 541a2d8199ff
Create Date: 2018-04-05 09:07:17.944018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c77036bbd97'
down_revision = '541a2d8199ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('birthday', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'birthday')
    # ### end Alembic commands ###
