"""empty message

Revision ID: bc5e7cba581f
Revises: 
Create Date: 2018-04-03 13:40:48.524252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc5e7cba581f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('pwd', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('info', sa.String(length=100), nullable=True),
    sa.Column('face', sa.String(length=255), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('face'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_user_addtime'), 'user', ['addtime'], unique=False)
    op.add_column('admin', sa.Column('addtime', sa.DateTime(), nullable=True))
    op.alter_column('admin', 'account',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('admin', 'nickname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('admin', 'pwd',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_admin_addtime'), 'admin', ['addtime'], unique=False)
    op.create_unique_constraint(None, 'admin', ['nickname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='unique')
    op.drop_index(op.f('ix_admin_addtime'), table_name='admin')
    op.alter_column('admin', 'pwd',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('admin', 'nickname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('admin', 'account',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('admin', 'addtime')
    op.drop_index(op.f('ix_user_addtime'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
