"""empty message

Revision ID: e978f118fd91
Revises: 26bec75584e5
Create Date: 2018-04-03 14:14:31.124749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e978f118fd91'
down_revision = '26bec75584e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('pwd', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('info', sa.String(length=100), nullable=True),
    sa.Column('face', sa.String(length=255), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('face'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_member_addtime'), 'member', ['addtime'], unique=False)
    op.create_table('memberlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberlog_addtime'), 'memberlog', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberlog_addtime'), table_name='memberlog')
    op.drop_table('memberlog')
    op.drop_index(op.f('ix_member_addtime'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
